# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180112_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
